### ISSUE TITLE
Problème de licence

### ISSUE THREAD

**Issue by mickaelandrieu** [TeamEver/everpsblog#1]
Hello,

en entête je vois pour la licence un "tous droits réservés": accepterais-tu de passer ta licence en AFL 3.0 (licence standard) ou MIT ?

En fait, à ce stade je ne suis pas sûr que nous ayons le droit d'utiliser ton module légalement.

Bien à toi,

**Comment by Ljz7** [comment]
Bonjour @mickaelandrieu, 

Merci pour cette remarque. Je partirais sur une licence GPL. 

Qu'est-ce que tu en penses @CySSoO ?

**Comment by CySSoO** [comment]
Aucun souci pour moi, la licence GPL me va bien. Je mettrai d'ailleurs le même type de licence sur les autres modules qui débarqueront tôt ou tard sur Github (et donc Ever Quotation pour commencer)
Tu peux t'en charger @Ljz7 ?

**Comment by mickaelandrieu** [comment]
Faudrait demander à Antoine de PrestaShop, il parait que GPL et PrestaShop sont pas compatibles, pourtant énormément de modules open source sont en GPL v3

**Comment by Ljz7** [comment]
Pareil, je ne m'y connais pas beaucoup. Je sais que GPL nous permettrait de "protéger" le code de ce module. Mais cela signifie aussi qu'il faudra surveiller ce qui se fait avec lui. Je ne pense pas qu'on le fera. En effet, elle n'est pas compatible avec Prestashop : https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/compatible-licenses/

AFL 3.0 serait la plus adéquate. C'est ce que Prestashop propose pour la contribution (https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/project-modules/). Ça n'est pas tout à fait de la contribution car le module n'est pas natif de Prestashop mais peut-être que ça peut coller. 

La licence MIT signifierait que le module et/ou le code du module pourrait être distribué/vendu par quiconque. Ça n'est pas l'idée.

@mickaelandrieu & @CySSoO , vous savez comment contacter Antoine de Prestashop pour lui demander plus d'info ?

**Comment by CySSoO** [comment]
@Ljz7 J'ai eu des retours, on part bien sur une licence AFL
Est-ce que tu pourrais la mettre en place s'il te plaît ?

**Comment by CySSoO** [comment]
Sala-sali-salut @mickaelandrieu 
J'ai changé la licence, tu pourrais me confirmer qu'elle te convient ?
Merci et à plouche :-)

**Comment by mickaelandrieu** [comment]
Hello @CySSoO,

c'est parfait merci à vous d'avoir fait l'effort.
