### ISSUE TITLE
Update module

### ISSUE THREAD

**Issue by Philippe-M** [TeamEver/everpsblog#11]
Hi

I have a Prestashop 1.7.8.7 instance which uses version 5.3.25 of your module.I would like to go to the last Version in order to take advantage of the password function.

Is there a particular process to achieve the update? During the update will all the parameters be preserved?

Thanks in advance.

**Comment by CySSoO** [comment]
Hello, 
There is no particular process apart from the native one of Prestashop and going to the module configuration
All settings will be preserved, the module will not erase data during an update
