### ISSUE TITLE
Error on install, not work config module ()

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everpsblog#12]
Error on install:

Integrity constraint violation: 1062 Duplicate entry '75-974-1' for key 'PRIMARY'

The config page for the module does not work.

![image](https://github.com/TeamEver/everpsblog/assets/31345705/ce5f85fd-6709-444c-b7a4-b947eaebf916)

Install on PS 8.1.2 with PHP 8.1.23 and apache 2.4.52.

Many thanks !!!

**Comment by CySSoO** [comment]
Hello @Luifer-dnk 
Could you try latest release ?
https://github.com/TeamEver/everpsblog/releases/tag/V5.5.11
This should resolve the issue

**Comment by Luifer-dnk** [comment]
Same error on intall:

![image](https://github.com/TeamEver/everpsblog/assets/31345705/3c074443-3289-4438-ac3a-94b46f174512)

But now i can access at config page.

I test on two install clean.

Many thanks !!!

**Comment by CySSoO** [comment]
Good morning
Could you try with the latest release available here?
https://github.com/TeamEver/everpsblog/releases/tag/V5.6.1
Thanks in advance

**Comment by Luifer-dnk** [comment]
> Good morning Could you try with the latest release available here? https://github.com/TeamEver/everpsblog/releases/tag/V5.6.1 Thanks in advance

![image](https://github.com/user-attachments/assets/e81d3f4b-e667-4737-9b70-e94ac12efbc6)

On front office.

**Comment by Luifer-dnk** [comment]
Fixed:

Add private on class:

![image](https://github.com/user-attachments/assets/585e22b4-0d75-4b91-a267-06bdfe7d035d)

**Comment by CySSoO** [comment]
Hello @Luifer-dnk 
I've just committed fix, thanks for all 👍

**Comment by Luifer-dnk** [comment]
Working !!!
