### ISSUE TITLE
Suggestion d'amélioration 

### ISSUE THREAD

**Issue by christophe-rouille** [TeamEver/everpsblog#3]
Bonjour,

Si on désactive les commentaires, il faudrait également ne pas afficher dans mon compte le bloc "Mes commentaires"

A priori en remplacant 
`<a class="col-lg-4 col-md-6 col-sm-6 col-xs-12" href="{$link->getModuleLink('everpsblog','customercomments')|escape:'htmlall':'UTF-8'}">
    <span class="link-item">
        <i class="fto-doc-text-inv mar_r4 fs_lg material-icons hvr-wobble-to-bottom-right">notifications_active</i>
        {l s='My comments' mod='everpsblog'}
    </span>
</a>
`
par 
`{if isset($allow_comments) && $allow_comments}
<a class="col-lg-4 col-md-6 col-sm-6 col-xs-12" href="{$link->getModuleLink('everpsblog','customercomments')|escape:'htmlall':'UTF-8'}">
    <span class="link-item">
        <i class="fto-doc-text-inv mar_r4 fs_lg material-icons hvr-wobble-to-bottom-right">notifications_active</i>
        {l s='My comments' mod='everpsblog'}
    </span>
</a>
{/if}`

Dans le fichier modules\everpsblog\views\templates\hook\my-account.tpl

ça à l'air d'être bon mais je ne sais pas si il y a d'autres impact ailleurs

Peut être bloquer complétement le controller customercomment en redirigeant vers une 404 si les commentaires ne sont pas activés ?

**Comment by CySSoO** [comment]
Bonjour et merci pour ce signalement
Un commit vient d'être réalisé. Le bloc ne s'affichera pas sur la partie "Mon compte" si les commentaires ne sont pas autorisés, et si un internaute cherche malgré tout à forcer l'accès, le controller le redirigera vers la page d'accueil
