### ISSUE TITLE
[Feature] password on post

### ISSUE THREAD

**Issue by Philippe-M** [TeamEver/everpsblog#5]
Hello,

In the next versions it could be interesting to allow the locking of a post by a password.

The objective is to allow access to a post thanks to a password in defined to certain visitors, this password is common to all visitors.

**Comment by CySSoO** [comment]
Hello,
The feature has just been added. Be careful however, the passwords are not restored in the admin for security reasons.
An override has been added for backward compatibility between Prestashop 8 and Prestashop 1.7, make sure it is in place if you are using Prestashop 1.7.
Do not hesitate to open an issue if you encounter any problems and thank you very much for participating in the improvement of this free Prestashop module.
Best regards
