### ISSUE TITLE
Notice: Undefined variable: meta_description

### ISSUE THREAD

**Issue by atila97** [TeamEver/everpsblog#6]
J'ai eu cet erreur au moment d'utiliser la pagination: ` ?page=2`
<img width="1219" alt="Capture d’écran 2023-04-14 à 22 53 28" src="https://user-images.githubusercontent.com/95034025/232152653-d94de3e2-c8ed-4201-9561-736b93098e2b.png">

à modifier par  `$meta_desc` 

https://github.com/TeamEver/everpsblog/blob/130d00a7703bb3b0b6509916931d95924a7b16d8/controllers/front/blog.php#L121

**Comment by CySSoO** [comment]
Hello
Je viens de faire des commits de fin de semaine, la correction est en place
Attention toutefois, un override a été mis en place afin de gérer une compatibilité PS 1.7 <=> PS 8
Merci en tout cas pour le signalement, et navré pour le délai de réponse
