### ISSUE TITLE
Error on install PS 8

### ISSUE THREAD

**Issue by Luifer-dnk** [TeamEver/everpsblog#7]
Error on install:

![image](https://github.com/TeamEver/everpsblog/assets/31345705/9c6b9090-3e5c-4d09-9031-87d87fac0eb1)

On debug mode !!!

PS 8.1.0 Release candidate.
PHP 7.3.33

Many thanks.

**Comment by CySSoO** [comment]
Thanks for these informations
Could you try again with the latest release?
Best regards

**Comment by Luifer-dnk** [comment]
On new version same.

It happens when the installation is done with the "debug mode" active.

This way it doesn't show the eve-blog side menu and shows hook errors.

PS v8.1.0 RC
PHP 8.1.20

On localhost and https// host real.

**Comment by CySSoO** [comment]
Hello again
I managed to reproduce the problem. Does the latest release fix the issue on your side as well?
Best regards

**Comment by Luifer-dnk** [comment]
Another hooks on install on debug mode.

![image](https://github.com/TeamEver/everpsblog/assets/31345705/5a7c02f3-8ee6-4f39-a699-a9c0d93c801b)

And on debug mode no permit reset module:

![image](https://github.com/TeamEver/everpsblog/assets/31345705/77da25fb-cb01-4646-98bc-35cc43812d85)

Many thanks for you work.

**Comment by Luifer-dnk** [comment]
Latest version 5.5.8 perfect !!!

PS 8.1.0 RC
PHP 8.1.20

On server "localhost" and server live https://...

Many thanks !!!

**Comment by CySSoO** [comment]
Great news !
Thanks for your feedback, feel free to open another issue if needed
Best regards
