### ISSUE TITLE
getLanguagesIds method missing

### ISSUE THREAD

**Issue by marinovivaylo** [TeamEver/everpsblog#8]
![25654264](https://github.com/TeamEver/everpsblog/assets/25131012/3ad40afd-6f61-4bf7-9977-cf6a6bb4606b)

**Comment by CySSoO** [comment]
Good morning
Can you try with the latest release of the module?
Thank you very much for your participation in improving this free Prestashop module
Best regards

**Comment by marinovivaylo** [comment]
The problem has been corrected. Thank you!

Now, however, after I save the post, it becomes password protected without me having set one.
![25654264](https://github.com/TeamEver/everpsblog/assets/25131012/63a58dae-0622-46b2-b323-2d54814a2e06)

**Comment by Luifer-dnk** [comment]
Yes.

Clean password:

![image](https://github.com/TeamEver/everpsblog/assets/31345705/9642f57d-c2c0-49b6-9f1a-24cd56e8f8d7)

But not show post:

![image](https://github.com/TeamEver/everpsblog/assets/31345705/564dad22-bab3-46ba-8a4e-323d668d42c7)

Greetings.

**Comment by CySSoO** [comment]
Could you tell me if latest release fix this bug ?
Best regards

**Comment by marinovivaylo** [comment]
@CySSoO - the last release fixed this issue. Thank you!

Best regards

**Comment by CySSoO** [comment]
Thanks for your feedback !
Feel free to open another issue if needed :-)
Best regards
